# Generated by Django 4.0.1 on 2022-01-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0003_remove_product_id_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_data',
            field=models.ImageField(upload_to='shop/'),
        ),
    ]
