# Generated by Django 4.0.1 on 2022-01-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0004_alter_product_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_data',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
