# Generated by Django 4.0.1 on 2022-01-23 08:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0006_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='product_name'),
        ),
    ]
