# Generated by Django 4.0.1 on 2022-01-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0007_alter_product_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
