# Generated by Django 4.0.1 on 2022-01-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0008_rename_product_slug_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_price',
            field=models.IntegerField(default=0),
        ),
    ]
