# Generated by Django 4.0.1 on 2022-01-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0009_product_buy_price_product_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='rent_price',
            field=models.IntegerField(default=200),
        ),
    ]
