# Generated by Django 4.0.1 on 2022-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0010_alter_product_buy_price_alter_product_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_data',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
